name: finguard_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.5.4
  provider: ^6.1.2
  uuid: ^4.5.1
  dio: ^5.9.1
  shimmer: ^3.0.0
  intl: ^0.20.2
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
