name: finguard
description: "Financial Guard apps"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.5.4
  provider: ^6.1.2
  uuid: ^4.5.1
  dio: ^5.9.1
  shimmer: ^3.0.0
  intl: ^0.20.2
  fl_chart: ^0.66.2
  flutter_svg: ^2.0.10
  alice: ^0.4.2
  google_sign_in: ^6.2.1
  package_info_plus: ^6.0.0
  url_launcher: ^6.3.1
  in_app_purchase: ^3.2.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/image/onboarding_intro.svg
    - assets/image/google_logo.svg
